  hTitle=get(gca,'title');
  hXLabel=get(gca,'xlabel');
  hYLabel=get(gca,'ylabel');
  
  set(gca,...
      'FontName', 'Helvetica'   , ...
      'Box'         , 'on'      , ...
      'XColor'      , [.2 .2 .2], ...
      'YColor'      , [.2 .2 .2], ...
      'FontSize'    , 12        , ... 
      'LineWidth'   , 1.2    , 'visible','on'     );
  set(hTitle,...
      'FontName'  , 'AvantGarde', ...
      'FontSize'  , 14          , ...
      'FontWeight', 'bold'      );
  set([hXLabel, hYLabel],       ...
      'FontName', 'Helvetica', ...
      'FontSize', 14          );

  if exist('hbar','var')
    set(hbar,'fontsize',12);
    set(get(hbar,'ylabel'),'fontsize',14);
  end
%